[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200


[[redirects]]
  from = "/TraficLight"
  to = "/"
  status = 200

  
[[redirects]]
  from = "/User_setings/*"
  to = "http://localhost:3005/User_setings/*"
  status = 200